version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node.js API service
  api:
    build:
      context: .
    container_name: node_app_container
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/dealershipDB
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: node app.js

volumes:
  mongo_data: {}
