services:
  - type: web
    name: drivenation
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn djangoproj.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: djangoproj.settings
